Calendar-Auto-Scheduler/calendarauto/urls.py
from django.urls import include, path

from . import views

app_name = 'calendarauto'
urlpatterns = [
    path('', views.CalendarView, name='temp_view'),
    path('<int:year>/<int:month>/<int:day>/', views.CalendarView, name='calendar_view'),
    path('Todo', views.TodoView.as_view(), name='todo'),
    path('<int:year>/<int:month>/<int:day>/results', views.add_new_task, name='add_new_task'),
    path('<int:year>/<int:month>/<int:day>/schedule', views.schedule_hour_block, name='schedule_hour_block'),
]

Calendar-Auto-Scheduler/project/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('calendarauto/', include('calendarauto.urls')),
    #path('<int:year>/<int:month>/',
    #     CalendarView.as_view(month_format='%m'),
    #     name="archive_month_numeric"),
]

Calendar-Auto-Scheduler/calendarauto/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta, datetime
from django.utils.timezone import make_aware

# Create your models here.

class GenericTask(models.Model):
    task_name = models.CharField(max_length=100, default = "None")
    task_description = models.CharField(max_length=300,default='None')
    deadline = models.DateTimeField('Deadline', null=True)
    do_after = models.DateTimeField('Do After', default=timezone.now, null=True) # Do the task by 
    est_time_to_complete = models.DurationField(default=timedelta(hours=1)) # Est time to complete
    completed = models.BooleanField(default=False) # Whether the task is completed or not
    location = models.CharField(max_length = 300) # The location of the task
    scheduled = models.BooleanField(default=False) # Whether the task is scheduled or not

    time_created = models.DateTimeField("Time Created", default=timezone.now)
    # Regulate so that the est task length can't be longer than the difference between
    # Do by and the deadline
    
    def __str__(self):
        return self.task_name + self.task_description + ". Due by " + str(self.deadline) + ". Start by " + str(self.do_after) + ". Duration: " + str(self.est_time_to_complete)

    def get_starting_deadline(self):
        if self.deadline == None:
            return make_aware(datetime.max - timedelta(days=365))
        return self.deadline - self.est_time_to_complete

    class Meta:
        get_latest_by = 'time_created'
        
class GenericHourBlock(models.Model):
    hour_type = models.CharField(max_length=2, default='BL') # The type of the hour
    datetime = models.DateTimeField('Hour Representative')
    isFilled = models.BooleanField(default=False)
    current_task = models.ForeignKey(GenericTask, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.hour_type + str(self.get_current_task())
    
    def is_hour(self, day, month, year, hour_start):
        return self.datetime.day == day and self.datetime.month == month and self.datetime.year == year and self.datetime.hour == hour_start
    
    '''
    Function to get the GenericHourBlock associated with this day, month, and year, and hour start.
    Assumes:
            0 < month < 13
            0 < day < 32
            0 <= hour < 23
            1 <= year <= 9999
    '''
    def get_hour(day, month, year, hour_start):
        objects = GenericHourBlock.objects.order_by('-datetime')
        # Binary search this list until you get to the Generic Hour Block.
        target = make_aware(datetime(hour=hour_start, month=month, year=year, day=day ))
        i = 0
        j = len(objects)
        while i < j:
            mid = (i + j)//2
            print(objects[mid].datetime, target,objects[mid].datetime < target )
            if objects[mid].datetime < target:
                j = mid - 1
            elif objects[mid].datetime > target:
                i = mid + 1
            else:
                return objects[mid]
        return None
    
    def populate(self):
        options = GenericTask.objects.all()
                                                    # if it starts before the block ends, it's an option!
        selection = [x.id for x in options if (x.do_after <= self.datetime + timedelta(hours=1) and self.datetime <= x.get_starting_deadline() and not x.scheduled)]
        refined_options = options.filter(id__in = selection)
        if len(refined_options):
            self.current_task = refined_options.earliest()
            self.current_task.scheduled = True
            self.isFilled=True
            self.current_task.save()
        if self.get_current_task() == None:
            for i in options:
                if i.do_after == None or i.deadline == None:
                    self.current_task = i
                    self.current_task.scheduled = True
                    self.isFilled=True
                    self.current_task.save()
                    break
        self.save()
        
    '''
    returns true for successful scheduling
    reutrns false for unsuccessful scheduling
    '''
    def schedule(self, specific_task):
        # If the task fits in the hour, schedule it! Return true for succeeded
        if (specific_task.do_after <= self.datetime  + timedelta(hours=1)) and (self.datetime <= specific_task.get_starting_deadline()) and not specific_task.scheduled:
            self.current_task = specific_task
            self.current_task.scheduled = True
            self.isFilled = True
            self.current_task.save()
            self.save()
            return True
        else:
            return False
    def unschedule(self):
        self.isFilled = False
        a = self.get_current_task()
        if a != None:
            a.scheduled = False
        return a
        
    def get_current_task(self):
        if hasattr(self, 'current_task'):
            return self.current_task
        else:
            return None
    
    

Calendar-Auto-Scheduler/calendarauto/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core import serializers
from django.contrib import messages
#from datetime import datetime, time
import datetime

from .models import GenericTask, GenericHourBlock
import sys

# If the url is going to use varibles, then they must be listed here
# in the function name if it is a custom view i.e. what we have here
def CalendarView(request, year, month, day):
    isValidDate = True
    try:
        datetime.datetime(year, month, day)
    except:
        isValidDate = False

    if (isValidDate):
        today = datetime.datetime(year, month, day)
    else:
        today = datetime.datetime.now()
        
    idx = (today.weekday() + 1) % 7
    sun = today - datetime.timedelta(idx)
    sat = today + datetime.timedelta(6 - idx)
    
    data = serializers.serialize("json", GenericHourBlock.objects.all())
    
    #if (list(GenericTask.objects.values())):
    #    print(list(GenericTask.objects.values()))
    # Function ifInvalidInfo
    # Call the functionsend_user_invalid_input
    
    return render(request, 'calendarauto/calendar.html', {'sunday' : sun, 
                                                          'saturday' : sat, 
                                                          'task_list' : list(GenericTask.objects.values()),
                                                          'hour_blocks' : list(GenericHourBlock.objects.values()),
                                                          'hour_info' : data,
                                                          })

    
class TodoView(generic.ListView):
    template_name = 'calendarauto/todolist.html'
    context_object_name = 'task_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return GenericTask.objects.order_by('-deadline')

def MysteryView(request):
    return render(request, 'calendarauto/calendar.html')
    
def create_generic_task(deadline, hours_to_complete,
                    completed=False,scheduled=False, time_created=None, location='Default',
                    task_name='Default', task_description='Default',
                    do_after = None):
    est_time = datetime.timedelta(hours=int(hours_to_complete), minutes=int((hours_to_complete % 1)*60))
    time_assigned = timezone.now() if time_created == None else time_created
    do_after = timezone.now() if do_after == None else do_after
    return GenericTask.objects.create(est_time_to_complete=est_time,
                                      time_created = time_assigned,
                                      scheduled = False,
                                      location = location,
                                      completed = False,
                                      do_after = do_after,
                                      deadline = deadline,
                                      task_description=task_description,
                                      task_name=task_name)

def get_datetime_from_post(post_string):
    year = int(post_string[:4])
    month = int(post_string[5:7])
    day = int(post_string[8:10])
    hr = int(post_string[11:13])
    minute = int(post_string[14:16])
    return timezone.make_aware(datetime.datetime(year=year, month=month, day=day, hour=hr, minute=minute))

# Repeat this function until the returned unscheduled task list
# equals the previous returned unscheduled task list.
def schedule_new_task(task):
    # First, try to fit the task in any of the existing hourblocks before the 
    # deadline of this task. return True if this works.
    hourblocks_before_deadline = GenericHourBlock.objects.filter(datetime_gte = timezone.make_aware(datetime.now()), datetime__lt = task.deadline)
    for block in hourblocks_before_deadline:
        block.schedule(task)
        if task.scheduled:
            return True
    
    # We know there wasn't enough space before the task deadline now
    # for this task. get all the hourblocks after the task deadline.
    # We will try to RESCHEDULE SCHEDULED TASKS to these blocks now.
    hourblocks_after_deadline = list(GenericHourBlock.objects.filter(datetime_gte = task.deadline,
                                                                     isFilled=False))
    
    # For each hourblock before the deadline of the task (in reverse
    # order), find out of it can be scheduled in any of the blocks remaining
    # in the unscheduled list. Reschedule it as far out as possible
    # to make more reschedulings possible.
    
    for block in hourblocks_before_deadline[::-1]:
        j = len(hourblocks_after_deadline) - 1
        while j >= 0:
            if hourblocks_after_deadline[j].schedule(block.current_task):
                block.unschedule()
                block.schedule(task)
                return True        
            j -= 1
    
    # If none of the blocks could get rescheduled to later,
    # But one can be done later, unschedule the block with the furthest
    # out deadline, replace that with the task, and return the now 
    # unscheduled 
    hourblock_furthest_deadline = list(GenericHourBlock.objects.filter(
        datetime_gte = timezone.make_aware(datetime.now()), 
        datetime__lt = task.deadline).order_by('current_task__deadline'))[-1]
    if hourblock_furthest_deadline.current_task.deadline > task.deadline:
        furthest_out_deadline_task = hourblock_furthest_deadline.unschedule()
        if hourblock_furthest_deadline.schedule(task):
            return furthest_out_deadline_task
    
    # return all remaining unscheduled tasks.
    # Function breakpoint analysis:
        #   There is an opening before the task deadline
        #   And after the hourblock do_after:
        #       Expected: Schedules the given task. No rescheduling.
        #   There are no openings after the task deadline.
        #       Expected: No reschedulings occur. Task is returned.
        #   There are openings after the task deadline, but no openings
        #   before the task deadline
        #       Expected: System attempts to reschedule 1 hourblock before
        #       task deadline to an hourblock after the task deadline.
        #       Returns nothing.
        #   There are no openings before the task deadline and no openings
        #   after the task deadline, but one task before task deadline
        #   Can be done later.:
        #       Expected: System unschedules the latest task that can be 
        #       Done later, schedules the current task for the now open
        #       hour block, and returns the now unscheduled task.
        #   There are no openings before the task deadline, no openings
        #   After the task deadline, and no tasks that have deadlines
        #   after the task deadline.
        #       Expected: Just returns the task we tried to schedule.
    return task

def add_new_task(request,year, month, day):
    print(sys._getframe().f_code.co_name)    
    # Upgrade add_new_task it makes the ceil of duration number of tasks 
    # So that tasks are at most an hour long.
    # Always get the time from the datetime function for the deadline
    do_after = get_datetime_from_post(request.POST['start_time'])
    deadline = get_datetime_from_post(request.POST['end_time'])
    task_duration = float(request.POST['duration'])-.0001
    # make sure the user didn't put an illegal time in.
    if datetime.timedelta(hours=task_duration // 1, minutes=int((task_duration % 1)*60))+ do_after > deadline:
        print('invalid.')
        return HttpResponseRedirect(reverse('calendarauto:calendar_view', args=(year, month, day)))
    print('attempted to save task')
    tasks = []
    for i in range(0, int(task_duration) + 1):
        print('saving task')
        task = create_generic_task(deadline, 1 if i < int(task_duration) else task_duration % 1, do_after=do_after,
                        task_name = request.POST['task_name'] + ('(' + str(i + 1) + '/' + str(int(task_duration) + 1) + ')' if task_duration > 1 else ''),
                        task_description=request.POST['task_desc'])
        task.save()
        tasks.append(task)
    current_datetime = timezone.make_aware(datetime.datetime.now())
    to_schedule = GenericHourBlock.objects.filter(datetime__gte = current_datetime, isFilled = False)
    
    # Schedule a task. 
    # If the task 
    for i in to_schedule: # Should probably automatically spread the task out
                            # across available days... TODO
                            # First, fix the deadline issue.
        i.populate()
        print(i)
    
    # Issue: If all the blocks between the current moment and the deadline of a new task
    # are filled, we can't effectively schedule the task.
    # If there are currently scheduled tasks that have deadline after this tasks',
    # unschedule them and reschedule them to a later time.
    
    # all of the tasks have the same deadline.
    deadline = tasks[0].deadline
    # Get all the hour blocks between the present moment and the task deadline.
    # (Reschedule as far out as possible so that we have enough time to complete)
    # only reschedule blocks that have a task with a deadline after
    # The new task's deadline
    hour_blocks = list(GenericHourBlock.objects.filter(datetime__gte = current_datetime, datetime__lt = deadline, current_task__deadline__gt = deadline).order_by('-datetime'))
    now_unscheduled_tasks = [] # The tasks we unscheduled from hour blocks to make room for the new tasks
    # Reverse order so we do first parts first and last parts last.
    j = len(hour_blocks)-1
    for task in tasks[::-1]:
        if j == -1:

Calendar-Auto-Scheduler/calendarauto/templates/calendarauto/calendar.html
{% load static %}
<!DOCTYPE html>

<html onClick="clickedPage(event)">
    <!-- Does load it is the name in the tab -->
    <head>
        <meta charset="utf-8">
        <title>Auto Calendar</title>
        <link rel="stylesheet" type="text/css" href="{% static 'calendarauto/styles.css' %}">
        <script type="text/javascript" src="{% static 'calendarauto/test.js' %}"></script>
    </head>
    <!-- Loads everything after this -->
    <body>
        <!-- Looks for the month variable and year variables
             sent in as contextes from the render in the views module
        --> 
        <h1>Week of {{ sunday|date:"F j, Y" }} - {{ saturday|date:"F j, Y" }} 
            <!-- <div class="openBtn"> -->
                <button class="openButton" onclick="openForm()"><strong>Create New Task</strong></button>
            <!-- </div> -->
        </h1>
        
        <div class="addTaskPopup">
            <div class="formPopup" id="popupForm">
                <form action="{% url 'calendarauto:add_new_task' sunday|date:"Y" sunday|date:"m" sunday|date:"d" %}" method=post class="addFormContainer"> 
                    {% csrf_token %}
                    <h2>Create New Task</h2>

                    <label for="task_name">
                        <strong>Task Name</strong>
                    </label>
                    <input type="text" id="task_name" placeholder="Your Task Name" name="task_name" required>
                    <label for="task_desc">
                        <strong>Task Description</strong>
                    </label>
                    <input type="text" id="task_desc" placeholder="Your Task Description" name="task_desc" required>
                    <label for="start_time">
                        <strong>Start Time</strong>
                    </label>
                    <input type="datetime-local" id="start_time" name="start_time">
                    <label for="end_time">
                        <strong>Deadline</strong>
                    </label>
                    <input type="datetime-local" id="end_time" name="end_time">
                    <label for="duration">
                        <strong>Duration</strong>
                    </label>
                    <input type="number" id="duration" placeholder="Duration Length" name="duration" step="0.01" required>
                    <input type="submit" class="btn">
                    <input value="Close" type="button" class="btn cancel" onclick="closeForm()">
                </form>
            </div>
        </div>
        
        
        <div class="schedulePopup">
            <div class="formPopup" id="schedulepopupForm">
                <form action="{% url 'calendarauto:schedule_hour_block' sunday|date:"Y" sunday|date:"m" sunday|date:"d" %}" id="scheForm" method=post class="scheFormContainer">
                {% csrf_token %}
                    <h2>Schedule New Task</h2>
                    <div>
                        <label for="taskType">
                            <strong>Task Type:</strong>
                        </label>
                        <select id="taskType" name="taskType" onChange="changeForm()">
                            <option value='SF'>Social Friend</option>
                            <option value='SR'>Social Relationship</option>
                            <option value='SA'>Social Family</option>
                            <option value='Tr'>Travel</option>
                            <option value='St'>Study</option>
                            <option value='Wk'>Work</option>
                            <option value='Er'>Errand</option>
                            <option value='Rd'>Read</option>
                            <option value='Hb'>Hobby</option>
                        </select>
                        <label for="curTasks">
                            <strong>Current Tasks:</strong>
                        </label>
                        <select id="curTasks" name="curTasks">
                            {% if task_list %}
                                {% for task in task_list %}
                                    {% if not task.scheduled %}
                                        <option>{{ task.task_name }}</option>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </select>
                        <br>
                        <label for="start_hour">
                            <strong>Start Hour</strong>
                        </label>
                        <input type="text" id="start_hour" name="start_hour" size="30" disabled>
                        <label for="end_hour">
                            <strong>End Hour</strong>
                        </label>
                        <input type="text" id="end_hour" name="end_hour" disabled>
                        <label for="sche_duration">
                            <strong>Duration</strong>
                        </label>
                        <input type="text" value="1hr" id="sche_duration" name="sche_duration" disabled>
                        <br>
                        <input type="checkbox" id="autofill" name="autofill">
                        <label for="autofill">
                            <strong>Autofill</strong>
                        </label>
                        <input type="checkbox" id="email" name="email">
                        <label for="email">
                            <strong>Email Notification</strong>
                        </label>
                    </div>
                    <input type="text" id="start_time1" name="start_time1" class="ghost">
                    <input type="text" id="end_time1" name="end_time1" class="ghost">
                    <input type="text" id="day_week" name="day_week" class="ghost">
                    <input type="text" id="DAY" name="DAY" class="ghost">
                    <div id="specForm">
                        <label for="friends">
                            <strong>Friend List:</strong>
                        </label>
                        <select id="friends" name="friends">
                        </select>
                        <label for="friend_desc">
                            <strong>Description:</strong>
                        </label>
                        <input type="text" id="friend_desc" name="friend_desc">
                        <label for="friend_loc">
                            <strong>Location:</strong>
                        </label>
                        <input type="text" id="friend_loc" name="friend_desc">
                    </div>
                    <button type="submit" class="btn">Schedule</button>
                    <button type="button" class="btn cancel" onclick="closeScheduleForm()">Close</button>
                </form>
            </div>
        </div>
        
        <div class="infoBox">
            <div class="formPopup" id="sche_infobox">
                <!-- Function should be changed to unschedule the current task that is attached to the GenericHourBlock -->
                <form action="{% url 'calendarauto:schedule_hour_block' sunday|date:"Y" sunday|date:"m" sunday|date:"d" %}" id="scheForm" method=post class="infoBoxContainer">
                {% csrf_token %}
                    <h2>Hour Block Info</h2>
                    <div>
                        <label id="scheTaskName">
                            
                        </label>
                        <label id="scheTaskType">
                            
                        </label>
                        <br>
                        <label id="scheTaskDesc">
                            
                        </label>
                        <br>
                        <label id="sche_start_hour">
                            
                        </label>
                        <label id="sche_end_hour">
                        
                        </label>
                        <br>
                        <label id="scheduled_duration">
                        
                        </label>
                        <br>
                        <label id="sche_deadline">
                        
                        </label>
                    </div>
                    <div id="scheSpecForm">
                    </div>
                    <button type="submit" class="btn">Unschedule</button>
                    <button type="button" class="btn cancel" onclick="closeScheInfoBox()">Close</button>
                </form>
            </div>
        </div>
        
        <div class="infoBox">
            <div class="formPopup" id="not_sche_infobox">
                <!-- Function should be changed to have the GenericHourBlock be chnaged to whatever hour block that it was
                changed to -->
                <form action="{% url 'calendarauto:schedule_hour_block' sunday|date:"Y" sunday|date:"m" sunday|date:"d" %}" id="scheForm" method=post class="scheFormContainer">
                {% csrf_token %}
                    <h2>Hour Block Info</h2>
                    <div>
                        <label for="notScheTaskType">Task Type:</label>
                        <select id="notScheTaskType" name="notScheTaskType">
                            <option value='SF'>Social Friend</option>
                            <option value='SR'>Social Relationship</option>
                            <option value='SA'>Social Family</option>
                            <option value='Tr'>Travel</option>
                            <option value='St'>Study</option>
                            <option value='Wk'>Work</option>
                            <option value='Er'>Errand</option>
                            <option value='Rd'>Read</option>
                            <option value='Hb'>Hobby</option>
                        </select>
                    </div>
                    <br>
                    <button type="submit" class="btn">Change Hour Type</button>
                    <button type="button" class="btn cancel" onclick="closeNotScheInfoBox()">Close</button>
                </form>
            </div>
        </div>
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li id="message{{ forloop.counter}}" class="ghost">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <div id="canvas_div">
            <canvas id="myCanvas" height="750" class="calendar" onClick="showBlock(event)">
                Your browser does not support the canvas element.
            </canvas>
            <!-- 
            <button id="button" class="calBtn">Whats up</button> 
            <button id="button" class="calBtn">Whats up</button> 
            <button id="button" class="calBtn">Whats up</button> 
            -->
            <div id="test_id" class="sys_messages">
                <ul id="message_list" class="message_list">
                </ul>
            </div>
        </div>
        
        <p id="demo"></p>
        <p id="temp"></p>
    </body>
<!-- Can later call in javascript -->
{{ sunday|json_script:'sunday' }}
{{ saturday|json_script:'saturday' }}
{{ task_list|json_script:'tasks'}}
{{ hour_blocks|json_script:'blocks'}}
{{ hour_info|json_script:'info'}}
{{ options|json_script:'options'}}
</html>

Calendar-Auto-Scheduler/calendarauto/templates/calendarauto/results.html
<h1>made it here</h1>

Calendar-Auto-Scheduler/calendarauto/templates/calendarauto/todolist.html
<!DOCTYPE html>

<html onClick="changeURL(event)">
    <!-- Does load it is the name in the tab -->
    <head>
        <meta charset="utf-8">
        <!-- 
        <title>My test page</title>
        -->
        
    </head>
    <body>
    {% if task_list %}
        <ul> 
        {% for task in task_list %}
            {% if task.scheduled %}
                <li style="color:green">[{{ task.task_name }}] {{ task.task_description }}: To do by {{ task.deadline }} and after {{ task.deadline }} . Will take {{ task.est_time_to_complete }} hours</li>

            {% else %}
                <li style="color:red">[{{ task.task_name }}] {{ task.task_description }}: To do by {{ task.deadline }} and after {{ task.deadline }} . Will take {{ task.est_time_to_complete }} hours</li>

            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <p>No tasks.</p>
    {% endif %}
    </body>
</html>
<script>
    function changeURL(event) {
        var x = event.clientX;
        var y = event.clientY;
        if (x > screen.width - 50) {
            var today = new Date();
            window.location.replace("http://127.0.0.1:8000/calendarauto/" + today.getFullYear() + "/" + (today.getMonth() + 1) + "/" + today.getDate() + "/");
        }
    }
</script>